import type { Language } from './content'

const accent = ''
const green = ''
const yellow = ''
const dim = ''
const reset = ''

const hr = `${accent}──────────────────────────────────────────────────────────────${reset}`

const section = (title: string) => `${accent}> ${title}${reset}`
const ok = (text: string) => `${green}[ OK ]${reset} ${text}`
const warn = (text: string) => `${yellow}[WARN]${reset} ${text}`
const muted = (text: string) => `${dim}${text}${reset}`

export const terminalLines: Record<Language, string[]> = {
  es: [
    `${accent}root@ubuntu:~#${reset} curl -fsSL https://hpsr.sh/setup.sh | bash`,
    '',
    hr,
    section('Selecciona idioma'),
    hr,
    '',
    'Idioma / Language',
    '  [1] Español (predeterminado)',
    '  [2] English',
    'Selection [1]: ',
    `${accent}╔══════════════════════════════════════════════════════════════╗${reset}`,
    `${accent}║${reset} hpsr.sh                                                      ${accent}║${reset}`,
    `${accent}║${reset} Bootstrap seguro para Debian/Ubuntu                          ${accent}║${reset}`,
    `${accent}║${reset} hpsr.mx | hopsersmerk.com | hopsersmerk.dev                  ${accent}║${reset}`,
    `${accent}╚══════════════════════════════════════════════════════════════╝${reset}`,
    '  Version          0.2.0',
    `  Accent           ${accent}#f2dfffff${reset}`,
    '  Report           /root/.server-setup/reports/hpsr-report-20260419-023712.md',
    '  Log              /root/.server-setup/logs/hpsr-setup-20260419-023712.log',
    '',
    'Este asistente te ayudara a asegurar y preparar este servidor.',
    muted('No se aplican cambios hasta la confirmacion final.'),
    '',
    'Presiona ENTER para continuar...',
    '',
    hr,
    section('VERIFICACIONES [1/9]'),
    hr,
    ok('Running as root'),
    ok('Supported distro detected: ubuntu 24.04'),
    ok('apt available'),
    ok('Network connectivity detected'),
    ok('SSH server configuration detected'),
    ok('Writable workspace: /root/.server-setup'),
    '',
    'Resumen del sistema',
    '  Hostname         ubuntu',
    '  Zona horaria     Etc/UTC',
    '  Puerto SSH       22',
    '  IP publica       203.0.113.42',
    '¿Continuar? [Y/n]: ',
    '',
    hr,
    section('METADATOS DE PAQUETES'),
    hr,
    ok('Package metadata updated'),
    '',
    hr,
    section('DEPENDENCIAS MINIMAS'),
    hr,
    ok('Installed installer dependencies: zip'),
    '',
    hr,
    section('INTEGRACION CON RESEND [2/9]'),
    hr,
    'Usa Resend para:',
    '- enviar un resumen de la configuracion',
    '- mostrar el reporte directamente en el cuerpo del correo',
    '- enviar opcionalmente credenciales/llaves como adjuntos cifrados',
    '',
    '¿Habilitar integracion con Resend? [y/N]: y',
    'API key de Resend: ',
    'Direccion remitente: notify@hpsr.dev',
    'Direccion destinataria: admin@example.test',
    '',
    'Ejecutando envio de prueba...',
    '',
    ok('La prueba de Resend fue exitosa'),
    '',
    hr,
    section('IDENTIDAD DEL SERVIDOR [3/9]'),
    hr,
    '',
    'Hostname',
    '  Actual           ubuntu',
    '¿Mantener el hostname actual? [Y/n]: n',
    'Nuevo hostname: hpsr-demo-l',
    '',
    'Zona horaria',
    '  Actual           Etc/UTC',
    '¿Intentar sugerencia automatica de zona horaria por IP? [Y/n]: n',
    '¿Mantener la zona horaria actual? [Y/n]: n',
    '',
    'Selecciona una region de zona horaria',
    '  [1] America',
    '  [2] Europe',
    '  [3] Asia',
    '  [4] Africa',
    '  [5] Pacific',
    '  [6] Etc',
    'Selection [1]: 1',
    '',
    'Selecciona la zona horaria',
    '  ...',
    '  [98] America/Mexico_City',
    '  [101] America/Monterrey',
    '  ...',
    'Selection [1]: 98',
    '',
    hr,
    section('USUARIO ADMINISTRATIVO [4/9]'),
    hr,
    'Nuevo usuario administrador: adminops',
    "Contrasena para el usuario 'adminops': ",
    'Confirmar contrasena: ',
    '',
    hr,
    section('CONFIGURACION DE ACCESO SSH [5/9]'),
    hr,
    '',
    'Selecciona como configurar el acceso SSH',
    '  [1] Generar un nuevo par de llaves en este servidor (recomendado)',
    '  [2] Pegar una llave publica existente',
    '  [3] Usar un archivo de llave publica existente en este servidor',
    'Selection [1]: ',
    '',
    'Selecciona el tipo de llave',
    '  [1] ed25519 (recommended)',
    '  [2] rsa',
    'Selection [1]: ',
    '',
    hr,
    section('ENDURECIMIENTO SSH [6/9]'),
    hr,
    '',
    'Politica de seguridad',
    '  Actual           22',
    `  Sugerido         ${accent}666${reset}`,
    '',
    'Nuevo puerto SSH [666]: ',
    ok('El acceso SSH de root sera deshabilitado'),
    ok('La autenticacion SSH por contrasena sera deshabilitada'),
    '',
    hr,
    section('FIREWALL [7/9]'),
    hr,
    '',
    'Puertos de entrada permitidos',
    `  SSH              ${accent}666/tcp${reset}`,
    '  HTTP             80/tcp',
    '  HTTPS            443/tcp',
    '',
    '¿Agregar puertos extra? [y/N]: ',
    '',
    hr,
    section('FAIL2BAN [8/9]'),
    hr,
    'Fail2ban protege SSH bloqueando IPs tras multiples intentos fallidos.',
    '',
    'Jaula SSH',
    '- bantime  : 1h',
    '- findtime : 10m',
    '- maxretry : 5',
    '',
    ok('Fail2ban sera habilitado'),
    '',
    hr,
    section('ACTUALIZACIONES AUTOMATICAS [9/9]'),
    hr,
    '¿Habilitar unattended-upgrades para parches de seguridad? [Y/n]: ',
    '',
    hr,
    section('REVISION FINAL'),
    hr,
    '',
    'Identidad',
    `  Hostname         ${accent}hpsr-demo-l${reset}`,
    '  Zona horaria     America/Mexico_City',
    '',
    'Acceso administrativo',
    '  Usuario          adminops',
    '  Contrasena       configurada',
    '  Sudo             enabled',
    '',
    'SSH',
    `  Puerto           ${accent}666${reset}`,
    '  Login root       deshabilitado',
    '  SSH por contrasena deshabilitado',
    '  Modo de llave    generate',
    '',
    'Firewall',
    '  UFW              enabled',
    '  Permitidos       666, 80, 443',
    '',
    'Seguridad',
    '  Fail2ban         enabled',
    '  Actualizaciones  yes',
    '',
    'Resend',
    '  Habilitado       yes',
    '  Estado           passed',
    "Aplica todos los cambios ahora. Escribe 'apply' o 'yes' para continuar: yes",
    '',
    hr,
    section('APLICANDO CAMBIOS'),
    hr,
    ok('Hostname updated to hpsr-demo-l'),
    ok('Timezone set to America/Mexico_City'),
    ok("Created user 'adminops'"),
    ok('Generated SSH key pair at /root/.server-setup/generated/ssh/hpsr-20260419-023712-hpsr-demo-l-adminops_ed25519'),
    ok('Installed public key for adminops'),
    ok('La llave SSH generada fue verificada contra authorized_keys'),
    ok('Backed up sshd_config to /root/.server-setup/backups/ssh/sshd_config-20260419-023712.bak'),
    ok('SSH configuration applied and validated'),
    ok('UFW configured'),
    ok('Fail2ban enabled for SSH'),
    ok('Unattended upgrades enabled'),
    ok('Time synchronization enabled with systemd-timesyncd'),
    ok('Installed base packages'),
    '',
    hr,
    section('ACCIONES POSTERIORES'),
    hr,
    '',
    'Resumen de llaves SSH administradas',
    '  Llaves previas de hpsr.sh reemplazadas 0',
    '  Llaves externas conservadas 0',
    `  Nueva llave hpsr.sh instalada ${accent}yes${reset}`,
    '  Fingerprint de la llave SHA256:EXAMPLEfR4jQ3w8K2mN7pL9xT0vB1cD2eF3gH4iJ5k',
    '',
    'Llave privada',
    '  Path             /root/.server-setup/generated/ssh/hpsr-20260419-023712-hpsr-demo-l-adminops_ed25519',
    '  Fingerprint de la llave SHA256:EXAMPLEfR4jQ3w8K2mN7pL9xT0vB1cD2eF3gH4iJ5k',
    '¿Imprimir ahora la llave privada en consola? [y/N]: y',
    '',
    `${accent}-----BEGIN OPENSSH PRIVATE KEY-----${reset}`,
    'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEZGVtbwAAAAAAAAABAAAAlwAAAAdzc2gtZW',
    'QyNTUxOQAAAEDEMOFAKEKEYMATERIALONLYFORWEBDEMOA1B2C3D4E5F6G7H8I9J0KLMN',
    'OPQRSTUVWXYZabcd1234567890EXAMPLEline02FAKEKEYMATERIALONLYFORWEBDEMO',
    'qrstuvwxyzABCDEFGHIJKLMN1234567890exampleline03FAKEKEYMATERIALONLYWEB',
    'DEMOZYXWVUTSRQPONMLKJIHGFEDCBA0987654321exampleline04FAKEKEYMATERIAL',
    'FORWEBDEMOabcdefghijklmNOPQRSTUVWXYZ1234567890exampleline05FAKEKEYEND',
    `${accent}-----END OPENSSH PRIVATE KEY-----${reset}`,
    '',
    '¿Confirmas que ya guardaste correctamente la llave privada? [y/N]: ',
    warn('La llave privada temporal se conservara en el servidor hasta que la guardes correctamente'),
    '¿Enviar reporte de configuracion por Resend? [Y/n]: Y',
    ok('Correo enviado por Resend'),
    '¿Enviar paquete cifrado de credenciales por Resend? [y/N]: y',
    '',
    'Contrasena del archivo:',
    `${accent}demo-archive-pass-49de9ef0${reset}`,
    ok('Correo enviado por Resend'),
    ok('Reporte Markdown generado en /root/.server-setup/reports/hpsr-report-20260419-023712.md'),
    ok('Los archivos temporales sensibles fueron eliminados automaticamente'),
    '',
    ok('Configuracion completada correctamente.'),
    '',
    `${yellow}Importante:${reset}`,
    '- Prueba el acceso SSH en una nueva terminal antes de cerrar esta sesion.',
    '- Llave privada: /root/.server-setup/generated/ssh/hpsr-20260419-023712-hpsr-demo-l-adminops_ed25519',
    `- Destino SSH: adminops@203.0.113.42 ${accent}(puerto 666)${reset}`,
    '- Reporte: /root/.server-setup/reports/hpsr-report-20260419-023712.md',
    '- Log: /root/.server-setup/logs/hpsr-setup-20260419-023712.log',
  ],
  en: [
    `${accent}root@ubuntu:~#${reset} curl -fsSL https://hpsr.sh/setup.sh | bash`,
    '',
    hr,
    section('Select language'),
    hr,
    '',
    'Language / Idioma',
    '  [1] Spanish (default)',
    '  [2] English',
    'Selection [1]: ',
    `${accent}╔══════════════════════════════════════════════════════════════╗${reset}`,
    `${accent}║${reset} hpsr.sh                                                     ${accent} ║${reset}`,
    `${accent}║${reset} Secure Debian/Ubuntu Bootstrap                             ${accent}  ║${reset}`,
    `${accent}║${reset} hpsr.mx | hopsersmerk.com | hopsersmerk.dev                ${accent}  ║${reset}`,
    `${accent}╚══════════════════════════════════════════════════════════════╝${reset}`,
    '  Version          0.2.0',
    `  Accent           ${accent}#f2dfffff${reset}`,
    '  Report           /root/.server-setup/reports/hpsr-report-20260419-023712.md',
    '  Log              /root/.server-setup/logs/hpsr-setup-20260419-023712.log',
    '',
    'This wizard will help you secure and prepare this server.',
    muted('No changes are applied until the final confirmation.'),
    '',
    'Press ENTER to continue...',
    '',
    hr,
    section('PRECHECK [1/9]'),
    hr,
    ok('Running as root'),
    ok('Supported distro detected: ubuntu 24.04'),
    ok('apt available'),
    ok('Network connectivity detected'),
    ok('SSH server configuration detected'),
    ok('Writable workspace: /root/.server-setup'),
    '',
    'System Snapshot',
    '  Hostname         ubuntu',
    '  Timezone         Etc/UTC',
    '  SSH Port         22',
    '  Public IP        203.0.113.42',
    'Continue? [Y/n]: ',
    '',
    hr,
    section('PACKAGE METADATA'),
    hr,
    ok('Package metadata updated'),
    '',
    hr,
    section('MINIMUM DEPENDENCIES'),
    hr,
    ok('Installed installer dependencies: zip'),
    '',
    hr,
    section('RESEND INTEGRATION [2/9]'),
    hr,
    'Use Resend to:',
    '- send a configuration summary',
    '- show the report directly in the email body',
    '- optionally send credentials/keys as encrypted attachments',
    '',
    'Enable Resend integration? [y/N]: y',
    'Resend API key: ',
    'From address: notify@hpsr.dev',
    'To address: admin@example.test',
    '',
    'Running test delivery...',
    '',
    ok('Resend test succeeded'),
    '',
    hr,
    section('SERVER IDENTITY [3/9]'),
    hr,
    '',
    'Hostname',
    '  Current          ubuntu',
    'Keep current hostname? [Y/n]: n',
    'New hostname: hpsr-demo-l',
    '',
    'Timezone',
    '  Current          Etc/UTC',
    'Try automatic timezone suggestion by IP? [Y/n]: n',
    'Keep current timezone? [Y/n]: n',
    '',
    'Select a timezone region',
    '  [1] America',
    '  [2] Europe',
    '  [3] Asia',
    '  [4] Africa',
    '  [5] Pacific',
    '  [6] Etc',
    'Selection [1]: 1',
    '',
    'Select timezone',
    '  ...',
    '  [98] America/Mexico_City',
    '  [101] America/Monterrey',
    '  ...',
    'Selection [1]: 98',
    '',
    hr,
    section('ADMINISTRATIVE USER [4/9]'),
    hr,
    'New admin username: adminops',
    "Password for user 'adminops': ",
    'Confirm password: ',
    '',
    hr,
    section('SSH ACCESS SETUP [5/9]'),
    hr,
    '',
    'Choose how to configure SSH access',
    '  [1] Generate a new key pair on this server (recommended)',
    '  [2] Paste an existing public key',
    '  [3] Use an existing public key file on this server',
    'Selection [1]: ',
    '',
    'Select key type',
    '  [1] ed25519 (recommended)',
    '  [2] rsa',
    'Selection [1]: ',
    '',
    hr,
    section('SSH HARDENING [6/9]'),
    hr,
    '',
    'Security Policy',
    '  Current          22',
    `  Suggested        ${accent}666${reset}`,
    '',
    'New SSH port [666]: ',
    ok('Root SSH login will be disabled'),
    ok('Password authentication will be disabled'),
    '',
    hr,
    section('FIREWALL [7/9]'),
    hr,
    '',
    'Allowed inbound ports',
    `  SSH              ${accent}666/tcp${reset}`,
    '  HTTP             80/tcp',
    '  HTTPS            443/tcp',
    '',
    'Add extra ports? [y/N]: ',
    '',
    hr,
    section('FAIL2BAN [8/9]'),
    hr,
    'Fail2ban protects SSH by banning IPs after repeated failed login attempts.',
    '',
    'SSH jail',
    '- bantime  : 1h',
    '- findtime : 10m',
    '- maxretry : 5',
    '',
    ok('Fail2ban will be enabled'),
    '',
    hr,
    section('AUTOMATIC UPDATES [9/9]'),
    hr,
    'Enable unattended-upgrades for security patches? [Y/n]: ',
    '',
    hr,
    section('FINAL REVIEW'),
    hr,
    '',
    'Identity',
    `  Hostname         ${accent}hpsr-demo-l${reset}`,
    '  Timezone         America/Mexico_City',
    '',
    'Administrative access',
    '  User             adminops',
    '  Password         configured',
    '  Sudo             enabled',
    '',
    'SSH',
    `  Port             ${accent}666${reset}`,
    '  Root login       disabled',
    '  SSH password auth disabled',
    '  Key mode         generate',
    '',
    'Firewall',
    '  UFW              enabled',
    '  Allowed          666, 80, 443',
    '',
    'Security',
    '  Fail2ban         enabled',
    '  Updates          yes',
    '',
    'Resend',
    '  Enabled          yes',
    '  Status           passed',
    "Apply all changes now. Type 'apply' or 'yes' to continue: yes",
    '',
    hr,
    section('APPLYING CHANGES'),
    hr,
    ok('Hostname updated to hpsr-demo-l'),
    ok('Timezone set to America/Mexico_City'),
    ok("Created user 'adminops'"),
    ok('Generated SSH key pair at /root/.server-setup/generated/ssh/hpsr-20260419-023712-hpsr-demo-l-adminops_ed25519'),
    ok('Installed public key for adminops'),
    ok('Generated SSH key verified against authorized_keys'),
    ok('Backed up sshd_config to /root/.server-setup/backups/ssh/sshd_config-20260419-023712.bak'),
    ok('SSH configuration applied and validated'),
    ok('UFW configured'),
    ok('Fail2ban enabled for SSH'),
    ok('Unattended upgrades enabled'),
    ok('Time synchronization enabled with systemd-timesyncd'),
    ok('Installed base packages'),
    '',
    hr,
    section('POST ACTIONS'),
    hr,
    '',
    'SSH key management summary',
    '  Previous hpsr.sh keys replaced 0',
    '  External keys preserved 0',
    `  New hpsr.sh key installed ${accent}yes${reset}`,
    '  Key fingerprint SHA256:EXAMPLEfR4jQ3w8K2mN7pL9xT0vB1cD2eF3gH4iJ5k',
    '',
    'Private key',
    '  Path             /root/.server-setup/generated/ssh/hpsr-20260419-023712-hpsr-demo-l-adminops_ed25519',
    '  Key fingerprint SHA256:EXAMPLEfR4jQ3w8K2mN7pL9xT0vB1cD2eF3gH4iJ5k',
    'Print private key to console now? [y/N]: y',
    '',
    `${accent}-----BEGIN OPENSSH PRIVATE KEY-----${reset}`,
    'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEZGVtbwAAAAAAAAABAAAAlwAAAAdzc2gtZW',
    'QyNTUxOQAAAEDEMOFAKEKEYMATERIALONLYFORWEBDEMOA1B2C3D4E5F6G7H8I9J0KLMN',
    'OPQRSTUVWXYZabcd1234567890EXAMPLEline02FAKEKEYMATERIALONLYFORWEBDEMO',
    'qrstuvwxyzABCDEFGHIJKLMN1234567890exampleline03FAKEKEYMATERIALONLYWEB',
    'DEMOZYXWVUTSRQPONMLKJIHGFEDCBA0987654321exampleline04FAKEKEYMATERIAL',
    'FORWEBDEMOabcdefghijklmNOPQRSTUVWXYZ1234567890exampleline05FAKEKEYEND',
    `${accent}-----END OPENSSH PRIVATE KEY-----${reset}`,
    '',
    'Confirm you have safely stored the private key? [y/N]: ',
    warn('Temporary private key will remain on the server until you store it safely'),
    'Send configuration report via Resend? [Y/n]: Y',
    ok('Email sent through Resend'),
    'Send encrypted credential bundle via Resend? [y/N]: y',
    '',
    'Archive password:',
    `${accent}demo-archive-pass-49de9ef0${reset}`,
    ok('Email sent through Resend'),
    ok('Markdown report generated at /root/.server-setup/reports/hpsr-report-20260419-023712.md'),
    ok('Temporary sensitive files were removed automatically'),
    '',
    ok('Configuration completed successfully.'),
    '',
    `${yellow}Important:${reset}`,
    '- Test SSH access in a new terminal before closing this session.',
    '- Private key: /root/.server-setup/generated/ssh/hpsr-20260419-023712-hpsr-demo-l-adminops_ed25519',
    `- SSH destination: adminops@203.0.113.42 ${accent}(port 666)${reset}`,
    '- Report: /root/.server-setup/reports/hpsr-report-20260419-023712.md',
    '- Log: /root/.server-setup/logs/hpsr-setup-20260419-023712.log',
  ]
}
